### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by ergofobe** [oberonsolutions/bitcore-node#1]
Create a Dockerfile that runs a custom bitcore-node in a container with both bitcoind and web services enabled.

In the future, as we build additional services for alt-coins, it should be possible to launch a container with an environmental variable such as "BLOCKCHAIN=litecoin" which would cause the container to launch a litecoind instead of bitcoind.

**Comment by daverod24** [comment]
listo  lo estoy   construyendo

**Comment by daverod24** [comment]
ya  lo   construí   estoy  igual  haciendo  unas   pruebas  de  como  lanzarlo  con  las   variables   pero  no  me  agarra 

commit  branch dev/dave #91067a4
